### PR TITLE
Only support public calling convention types.

### PR DESCRIPTION
**Pull request by 333fred**

### CODE REVIEW

**Comment by 333fred** [comment]
Practically, this only means that the runtime cannot define an internal calling convention usable only from within corelib.

**Comment by jkotas** [comment]
Just curious - is there a motivation for limiting this?

**Comment by 333fred** [comment]
> Just curious - is there a motivation for limiting this?

It simplifies implementation and we can't think of a motivating reason to have support.

**Comment by AaronRobinsonMSFT** [comment]
> > Just curious - is there a motivation for limiting this?
> 
> It simplifies implementation and we can't think of a motivating reason to have support.

I would also imagine it simply puts effort on people to use `Reflection.Emit` or some other hackery to gain access to the type.

**Pull request merged**
