### PR TITLE
Fixed class name in IAsyncEnumerable example.

### PR DESCRIPTION
**Pull request by kadamgreene**

### CODE REVIEW

**Comment by kadamgreene** [comment]
I noticed an issue with the name of an internal class in one of the IAsyncEnumerable examples.  Fixed it.

**Comment by jcouv** [comment]
Change looks good, but there is now a conflict, so cannot merge the PR as-is.

**Comment by jcouv** [comment]
@kadamgreene Change looks good, but there is now a conflict, so cannot merge the PR as-is.

**Review by jcouv — APPROVED** [review]
LGTM Thanks

**Comment by jcouv** [comment]
Fixed in https://github.com/dotnet/csharplang/commit/cc0831a7e9ec163b60002521bb84c68a3b6f9fff. Thanks for pointing out this

**Pull request closed without merging**
