### PR TITLE
Tweak C# version history

### PR DESCRIPTION
**Pull request by patricka2**
This page is include C# and Visual Studio version that shipped with, this unnecessary description destroy Uniformity of C# 8 with other C# version in this page.

### CODE REVIEW

**Comment by jcouv** [comment]
@patricka2 Since you're opening a duplicate PR, I can imagine that you are frustrated with the phrasing of the entry for C# 8.0 and you might be a little upset that we didn't accept your previous PR to change it.
There was a deliberate change in the 8.0 release of C# to only support Core 3.0 platform. It is correct *and important* to call that restriction out (*because* it is not uniform/regular), as it may surprise some users.
I hope you understand.

Regards,
Julien

**Comment by patricka2** [comment]
OK, I agree and i made another commit to fix its grammar. please merge this.

**Comment by yaakov-h** [comment]
I don't think changing "with" to "and" conveys the same meaning.

**Comment by patricka2** [comment]
Same meaning isn't problem , correct word for this case is "and".

**Comment by yaakov-h** [comment]
"and" implies an either/or relationship in this context as common vernacular. "with" means you need both.

Though you can use C# 8 with .NET Core 3.0 _and without Visual Studio_, but 16.3 is the earliest version to support it.

**Comment by patricka2** [comment]
It's simple, we don't need both so correct word is "and" in this case.

**Comment by patricka2** [comment]
I totally Convinced, Thank you @yaakov-h

**Comment by patricka2** [comment]
I totally convinced, Thank you @yaakov-h

**Comment by patricka2** [comment]
It's simple, we don't need both, so correct word is "and". @yaakov-h

**Comment by patricka2** [comment]
My English is weak, Is it necessary to use "the" int this case like "C# 8.0 - Visual Studio 2019 version 16.3 with the .NET Core 3.0" in this case or correct form is without "the"?

**Comment by patricka2** [comment]
However, I think Correct word is "and" because we can use C# 8 without visual studio

**Comment by patricka2** [comment]
Please merge new commit.

**Comment by patricka2** [comment]
My English is weak, if the correct word is "and" it's not problem, but if "with" is correct **I think** we need place "the" before "with" like this: "with the .NET Core 3.0".

**Comment by patricka2** [comment]
My English is weak, if the correct word is "and" it's not problem, but if "with" is correct It's not necessary to place a "the" after "with" like this: "with the .NET Core 3.0"?

**Comment by patricka2** [comment]
My English is weak, if the correct word is "and" it's not problem, but if "with" is correct It's not necessary to place a "the" after "with" ??? like this: "with the .NET Core 3.0"

**Comment by patricka2** [comment]
My English is weak, if the correct word is "and" it's not problem, but if "with" is correct It's not necessary to place a "the" after "with" like this: "with the .NET Core 3.0"?

**Comment by patricka2** [comment]
@333fred

**Comment by patricka2** [comment]
Please someone answer me.

**Comment by CyrusNajmabadi** [comment]
@patricka2 Please be patient.  People have lots of stuff on their plates.  Updating a single word in a doc isn't necessarily high pri for people.  Thanks! :)

**Comment by patricka2** [comment]
OK, But I do not think this case take a lot of time. @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
> OK, But I do not think this case take a lot of time. @CyrusNajmabadi

Please be patient.  People have important work they're all doing.  They may have absolutely no time to work on stuff outside of that.

**Comment by patricka2** [comment]
OK, I do not think this case take a lot of time but this single word really make me hurt :) @CyrusNajmabadi

**Comment by jcouv** [comment]
I agree that the current phrasing is not the best. I'm struggling to come up with something clearly better.

What do you think about ".NET Core 3.0 and Visual Studio 2019 version 16.3" instead, since Core 3 is the central part?

**Comment by patricka2** [comment]
> What do you think about ".NET Core 3.0 and Visual Studio 2019 version 16.3" instead, since Core 3 is the central part?

I think ".NET Core 3.0 and Visual Studio 2019 version 16.3" destroy uniformity with other version, and I think "Visual Studio 2019 version 16.3 and .NET Core 3.0" is the best (my commit)

**Comment by patricka2** [comment]
I think ".NET Core 3.0 and Visual Studio 2019 version 16.3" destroy uniformity with other version, and I think "Visual Studio 2019 version 16.3 and .NET Core 3.0" is better (my commit)

**Comment by patricka2** [comment]
> What do you think about ".NET Core 3.0 and Visual Studio 2019 version 16.3" instead, since Core 3 is the central part?

I think "Visual Studio 2019 version 16.3 and .NET Core 3.0" is better, placing VS version after .NET destroy uniformity with other C# version in this doc.

And i think **if** it isn't necessary to place a "the" before ".NET Core 3.0" (i am not sure "the" is necessary or not) this document **does not need** any change.

**Comment by patricka2** [comment]
> What do you think about ".NET Core 3.0 and Visual Studio 2019 version 16.3" instead, since Core 3 is the central part?

Placing VS version after .NET destroy uniformity with other C# versions in this doc, i think "Visual Studio 2019 version 16.3 and NET Core 3.0" (my commit) is better.

And I think **if it isn't necessary** to place a "the" before ".NET Core 3.0" (i am not sure "the" is necessary or not) this document **does not need any change**.

**Comment by patricka2** [comment]
It's necessary to place a "the" before ".NET Core 3.0" in "Visual Studio 2019 version 16.3 with .NET Core 3.0"?

**Comment by patricka2** [comment]
> What do you think about ".NET Core 3.0 and Visual Studio 2019 version 16.3" instead, since Core 3 is the central part?

I totally disagree, placing VS version after .NET destroy uniformity with other C# versions in this doc, i think "Visual Studio 2019 version 16.3 and NET Core 3.0" (my commit) is better.

 And I think if it isn't necessary to place a "the" before ".NET Core 3.0" (i am not sure "the" is necessary or not) this document does not need any change.

**Comment by patricka2** [comment]
Is it necessary to place a "the" before ".NET Core 3.0" in "Visual Studio 2019 version 16.3 with .NET Core 3.0" or "the" is additional?

**Comment by patricka2** [comment]
> What do you think about ".NET Core 3.0 and Visual Studio 2019 version 16.3" instead, since Core 3 is the central part?

I totally disagree, placing VS version after .NET destroy uniformity with other C# versions in this doc, i think "Visual Studio 2019 version 16.3 and NET Core 3.0" (my commit) is better.

And i think **if it isn't necessary** to place a "the" before ".NET Core 3.0" (i am not sure "the" is necessary or not) this document **does not need any change**.

**Comment by patricka2** [comment]
Is it necessary to place a "the" before ".NET Core 3.0" in "Visual Studio 2019 version 16.3 with .NET Core 3.0" or "the" is additional?

**Comment by CyrusNajmabadi** [comment]
> destroy uniformity with other C# versions in this doc

I don't know what this means. 

Reading the doc, things are clear. I would just leave things as they are.

**Comment by patricka2** [comment]
I am OCD and this things really make me hurt.

**Comment by patricka2** [comment]
I am OCD and this things really make me hurt. @CyrusNajmabadi

**Comment by patricka2** [comment]
It mean previous version only include VS version and in C# 8.0 id different in this doc. @CyrusNajmabadi

**Comment by HaloFour** [comment]
I agree that `with` does a better job of conveying the nuance of difference in behavior.

> I am OCD and this things really make me hurt.

I'd suggest that this energy is better spent elsewhere.  Nitpicking over tiny aspects of grammar to achieve a perceived goal of uniformity or whatever is not going to get much attention, and opening multiple PRs with comments that mention team members directly is more likely to turn people off from your contributions than anything else.

**Comment by patricka2** [comment]
I just want to have better docs and i am sorry for i got your time.

**Comment by patricka2** [comment]
> I don't know what this means.

I take it back, ".NET Core 3.0 and Visual Studio 2019 version 16.3" could be a good option.

**Comment by CyrusNajmabadi** [comment]
> I am OCD and this things really make me hurt. @CyrusNajmabadi

I'm sorry about that.  I'm just being honest in my assessment though.  When i read "C# 8.0 - Visual Studio 2019 version 16.3 and .NET Core 3.0", i don't see any problem at all with that phrasing.  It's clear and concise to me.  I'm not certain why it wouldn't be totally fine to use.

**Comment by patricka2** [comment]
For clarity, last commit in this doc it's by me #2856 (it merged). In #2856 i change C# 8.0 to "Visual Studio 2019 version 16.3 with .NET Core 3.0" after that i think "with .NET Core" may cause someone think for use C# 8.0 we need **both** VS and .NET (That's wrong) so i made this pull.

**Comment by jcouv** [comment]
Done. Glad this is sorted out. 
Cheers

**Pull request merged**
