### PR TITLE
Add singleton proposal for C# language

### PR DESCRIPTION
**Pull request by csblo**

### CODE REVIEW

**Comment by HaloFour** [comment]
Proposals should be submitted as Issues and discussed before a PR is submitted.  Any proposal needs to be "championed" by a member of the design team in order to be considered.

https://github.com/dotnet/csharplang#design-process

**Comment by theunrepentantgeek** [comment]
The singleton pattern is more of a *runtime policy* than anything else; enforcement within the language eliminates a lot of useful possibilities - such as unit testing, singleton-per-request, singleton-per-transaction, and so on.

**Comment by DanFTRX** [comment]
Is this just a lazy loaded readonly?

**Comment by csblo** [comment]
Thanks for comments, after reading them, I don't think that I'll maintain my proposal.

**Pull request closed without merging**
