### PR TITLE
Proposal for supporting pointer types in null coalescing operators

### PR DESCRIPTION
**Pull request by Jay-Madden**
This proposal is linked with championed issue #418

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/csharplang?pullRequest=3647) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/csharplang?pullRequest=3647) before we can accept your contribution.<br/><br/>:x: Jay-Madden [sign now](https://cla.dotnetfoundation.org/dotnet/csharplang?pullRequest=3647)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/csharplang?pullRequest=3647) it.</sub>

**Comment by 333fred** [comment]
You should probably add a mention that the existing rules for `??=` don't actually forbid pointer types as the type of `A`, even though we didn't implement that and I didn't intend it that way :).

**Comment by Jay-Madden** [comment]
Does that mean the ??= spec also needs changing or can it be left undefined?

**Comment by 333fred** [comment]
> Does that mean the ??= spec also needs changing or can it be left undefined?

I think it's probably fine for now.

**Comment by 333fred** [comment]
Thanks @Jay-Madden!

**Pull request merged**
