### PR TITLE
[BrokenLinksH2] Fixed the link path

### PR DESCRIPTION
**Pull request by v-sidlama**
Deleted the deprecated target.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This link works: https://vstfdevdiv.corp.microsoft.com/DevDiv2/DevDiv/_workitems/edit/529603

**Review by v-sidlama — COMMENTED** [review]
link update

**Comment by v-sidlama** [comment]
> This link works: https://vstfdevdiv.corp.microsoft.com/DevDiv2/DevDiv/_workitems/edit/529603

Thank you. Updated accordingly.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks :)

**Pull request merged**
