### PR TITLE
Update syntax to `await foreach`

### PR DESCRIPTION
**Pull request by jcouv**
FYI @stephentoub 
I'll go ahead and merge straight away.

### CODE REVIEW

**Comment by NinoFloris** [comment]
Ooh, curious, could you point me/us to any relevant info why this was changed?

**Comment by stephentoub** [comment]
> Ooh, curious, could you point me/us to any relevant info why this was changed?

@agocke has notes he'll be posting I believe.

**Comment by jcouv** [comment]
@NinoFloris The notes likely won't be very detailed for that decision.
Between `async` and `await`, there is clear precedent for `await` indicating where some waiting happens. That's the "easy" part.
Between `await foreach/using` and `foreach/using await` there was a decision based on taste rather than a definitive rationale (that I can recall). Personally, I preferred `foreach await` a little.

**Comment by jcouv** [comment]
@alrz Would you have a pointer for TS/ES? Are you saying they use `foreach await` or `await foreach`?

**Comment by CyrusNajmabadi** [comment]
@jcouv see: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html

> Finally, ES2015 introduced the for..of statement as a means of iterating over an iterable. Similarly, the Async Iteration proposal introduces the for..await..of statement to iterate over an async iterable:

```ts
async function f() {
  for await (const x of g()) {
     console.log(x);
  }
}
```

**Comment by alrz** [comment]
Thanks Cyrus. that being said, I think await foreach would definitely come off a as a surprise.

**Comment by markusschaber** [comment]
In my eyes, `await foreach` looks like the whole foreach loop is run asynchroneously and awaited as a whole, while `foreach await` awaits "inside" the loop. :-)

**Comment by YairHalberstadt** [comment]
@markusschaber
Exactly my thoughts

**Pull request merged**
