### PR TITLE
Fix documentation-comment.md urls

### PR DESCRIPTION
**Pull request by wtg-mg8**
Update urls from /draft-v6/ to /standard-v6/. This allows the url hashes to be preserved when clicking the links.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/csharplang?pullRequest=6856) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/csharplang?pullRequest=6856) before we can accept your contribution.<br/><br/>:x: WTG-MG8 [sign now](https://cla.dotnetfoundation.org/dotnet/csharplang?pullRequest=6856)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/csharplang?pullRequest=6856) it.</sub>

**Review by 333fred — COMMENTED** [review]
@BillWagner would you prefer these point to standard-v6, or draft-v7? Or is there a `latest-standard`/`latest-draft` branch we could point to instead?

**Comment by WTG-MG8** [comment]
FYI, the text at the start of [documentation-comments](https://github.com/dotnet/csharplang/blob/main/spec/documentation-comments.md) currently mentions it points to the csharp v6 version of the document.

**Review by jcouv — APPROVED** [review]

**Review by 333fred — CHANGES_REQUESTED** [review]
Putting a hold until Bill can respond.

**Comment by BillWagner** [comment]
My intent when I made these updates was to point to the corresponding version of the ECMA spec. The last point when the Microsoft spec and the ECMA spec were different documents was version 6. 

> would you prefer these point to `standard-v6`, or `draft-v7`? Or is there a `latest-standard`/`latest-draft` branch we could point to instead?

The ECMA committee chose to have versioned branches, and change the default branch as we move to actively working on different versions. We felt that would be better to create links that were always for a known version.

When we change the branch name from `draft-` to `standard-`, GitHub does provide redirects for us. This change, while helpful, isn't strictly required. 

I'm fine with merging it. The `standard-v6` is the name for this branch going forward.

**Review by 333fred — APPROVED** [review]
Thanks Bill

**Comment by 333fred** [comment]
Thanks for the pr @wtg-mg8!

**Pull request merged**
