### PR TITLE
Reverse the order

### PR DESCRIPTION
**Pull request by eyalsk**
Recent features/changes should appear first as opposed to last.

### CODE REVIEW

**Comment by jcouv** [comment]
I'm okay with the proposed ordering (newest at the top). Tagging @jaredpar @gafter @MadsTorgersen for second thought.

**Comment by jaredpar** [comment]
Makes sense to me.

**Comment by jcouv** [comment]
@eyalsk We'll go ahead with the ordering you proposed. But it seems there were changes made in the repo file since you proposed this change. Would you mind resolving the conflicts? Thanks

**Comment by eyalsk** [comment]
@jcouv Done.

**Comment by jcouv** [comment]
Thanks @eyalsk !
I'll go ahead and merge/squash.

**Pull request merged**
