### PR TITLE
Fix old mention of foreach await in async-streams

### PR DESCRIPTION
**Pull request by slang25**
Credit to Marc Gravell for spotting

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @jcouv

**Comment by jcouv** [comment]
The current (tentative) syntax has not changed. It is still `foreach await (...)` as far as I know.
I think @stephentoub made a mistake in updating the proposal.

Closing. Thanks

**Comment by stephentoub** [comment]
Ah, somehow I got it in my head that we changed that. Will fix.

**Comment by CyrusNajmabadi** [comment]
👍 on changing the syntax :)   @jcouv knows my opinions here.

**Comment by slang25** [comment]
Thanks all for the clarification

**Pull request closed without merging**
