### PR TITLE
Add proposal readonly local variables and method parameters

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

Hi all,

I write a basic proposal for `readonly` local variables and method parameters. (see #188)

### CODE REVIEW

**Comment by jnm2** [comment]
What does ITNOA mean?

**Comment by svick** [comment]
There's already another proposal here: https://github.com/dotnet/csharplang/pull/381.

**Comment by soroshsabz** [comment]
@svick Oh yes, what can I do? can I merge these patches together? or another fork from #381 PR?

**Comment by alrz** [comment]
As it's mentioned in the README.md,

>For new feature proposals, however, please raise them for discussion, and only submit a proposal as a pull request if invited to do so by a member of the Language Design Team (a "champion").

**Comment by soroshsabz** [comment]
@alrz So I close it.

**Pull request closed without merging**
