### PR TITLE
Proposal: Simplified parameter null validation

### PR DESCRIPTION
**Pull request by jaredpar**
This is a proposal that was discussed by LDM on 2019/1/14. Will link to LDM notes when they're available.

Note: sorry for getting this out same day as LDM meeting. It's a small proposal, got tied up last week and didn't finish writing until shortly before our LDM meeting.

### CODE REVIEW

**Comment by orthoxerox** [comment]
> Implicit property setter arguments

Could `!` be placed on `set` to indicate a null check?

```c#
public Foo Foo {get; set!;}
public Bar Bar {
    get { return bar; }
    set! { bar = value; DoSomethingElse(); }
}
```

**Comment by orthoxerox** [comment]
@YairHalberstadt I don't think features that help violate LSP are a good idea.

**Comment by YairHalberstadt** [comment]
@orthoxerox
CoreFX is full of NotSupportedExceptions. They violate LSP in exactly the same way.

**Comment by jaredpar** [comment]
@orthoxerox 

> Could ! be placed on set to indicate a null check?

Let me think on that. There is nothing wrong with this but I'm worried if it will be obvious enough that it applies to `value`.

**Comment by jaredpar** [comment]
@YairHalberstadt 

> When overloading a method that accepts a nullable value, it makes perfect sense to say that you intend to throw on a null value.

The scenario you outlined in the code is overriding though, not overloading. The NRT will issue a warning for that scenario as you're restricting the input set in the override, not expanding it. The language only allows for co / contravariant changes to nullable types in overrides.

**Comment by YairHalberstadt** [comment]
@jaredpar
Sorry that was a typo. I meant overriding.

There are many libraries (including in CoreFX) that throw a NotSupportedException on certain overrides.

Throwing a Null argument exception on a null parameter on an override where the base accepts a nullable parameter is not all that different.

**Comment by jaredpar** [comment]
@YairHalberstadt 

> Throwing a Null argument exception on a null parameter on an override where the base accepts a nullable parameter is not all that different.

I tend to agree with this. I wasn't in favor of issuing a warning for this case but LDM essentially decided the other way. If there is enough real world evidence this is common then LDM will reconsider their position.

**Comment by CyrusNajmabadi** [comment]
@jaredpar @jcouv If/when this gets done, we should have the appropriate IDE features light up.  Off the top of my head:

1. "add null check" should be updated to use this form.
2. We should have an analyzer that looks for the idiomatic forms for throwing null, and convert to use this. 

For '2' that would be things like looking for:

```c#
    if (name is null) {
        throw new ArgumentNullException(...);
    }
```

As well as the current IDE recommended form of:

```c#
    someThing = name ?? throw new ArgumentNullException(...);
```

From the IDE perspective we can debate what can be in those `...` sections.i.e. if we need to strictly look for something, or if the pattern can loosely match.

**Comment by tannergooding** [comment]
@jaredpar, has there been any consideration into having this emit a call to a throw helper (possibly on `PrivateImplementationDetails`) instead of directly emitting the throw (e.g. https://source.dot.net/#System.Private.CoreLib/shared/System/ThrowHelper.cs,170)?

Throwing the exception directly generates quite a bit of IL (and, in turn, assembly), which can hurt things like inlinability, codegen, and throughput.

**Comment by orthoxerox** [comment]
@CyrusNajmabadi what about an analyzer that goes "you have a non-nullable reference type parameter in your public API, consider adding a null check to ensure it's never null"?

**Comment by jaredpar** [comment]
@tannergooding 

> has there been any consideration into having this emit a call to a throw helper

No but it seems reasonable.

**Comment by YairHalberstadt** [comment]
> I tend to agree with this. I wasn't in favor of issuing a warning for this case but LDM essentially decided the other way. If there is enough real world evidence this is common then LDM will reconsider their position.

`IDictionary<TKey, TValue>` might be an example of this. There are dictionaries which accept a null key, but `Dictionary` does not. So is it better to have IDictionary accept a null key, and Dictionary throw on null, or have IDictionary not accept a null key, or even have a new interface `INullableKeyDictionary` which inherits `IDictionary`?

**Comment by YairHalberstadt** [comment]
Note, I'm not pushing for there to be no warning in such a case. I'm just trying to raise the issue so it is considered properly.

**Comment by svick** [comment]
Will an `async` method that uses this feature throw an exception or return a faulted `Task`?

Directly throwing an exception would be kind of consistent with how constructors and iterators throw the exception as soon as possible, even sooner than any user code can. In the case of `async`, it would mean that the exception would be thrown even before the `Task` that's returned from the method is `await`ed.

**Comment by svick** [comment]
@theunrepentantgeek If you have code like `async Task M() => throw new Exception();`, then it indeed runs synchronously. But it synchronously returns a faulted `Task`, it does not directly throw an exception.

So, if this feature directly threw an exception for `async` methods, it would *not* be the same as writing the checks manually  as the first lines of the `async` method.

**Comment by alrz** [comment]
I think in a `#nullable` context, in the absence of `!` on the parameter, we should emit an Assert anyways, because NRT is never definite and can be hijacked in a lot of ways. in that scenario, it's still possible to end up with a NRE down the call stack which could be hard to reason about. This is along the same line of https://github.com/dotnet/csharplang/issues/2149 which suggests to emit an assertion via null-suppression operators.

**Comment by theunrepentantgeek** [comment]
> we should emit an Assert anyways, because NRT is never definite and can be hijacked in a lot of ways.

This would upset the (very vocal) crowd who care about every wasted pico-second for performance reasons.

I like the idea of having a spec of syntax to write the null check for me - but it needs to be opt-in; I'd make extensive use of it at the borders of my libraries, but not internally.

**Comment by HaloFour** [comment]
@theunrepentantgeek 

> This would upset the (very vocal) crowd who care about every wasted pico-second for performance reasons.

By using `Debug.Assert` (or a similar helper function) those checks would only apply to builds where the `DEBUG` preprocessor is defined.  You'd reclaim those lost picoseconds by switching to a release build.

**Comment by HaloFour** [comment]
@theunrepentantgeek 

> When I specify that my method parameters are enforced, they better be enforced in production - for that's where it's most important to get a good stack trace to diagnose problems.

I agree.  That's what the `!` suffix on the parameter would do, add an always-enforced null-check.  I believe that @alrz is suggesting using these conditional helpers to throw for other NRTs situations, like a non-nullable parameter that *isn't* adorned with the `!` suffix, so that you can catch potential issues easier when debugging and testing.

Personally I'm on the fence about that as it can result in the application behaving differently depending on whether `DEBUG` is defined.

**Comment by alrz** [comment]
it can result in the application behaving differently depending on whether DEBUG is defined.

It's not behavioural difference, it's just an elided check. we already use Debug.Assert in Roslyn extensively, and it hasn't been a source of confusion?

**Comment by yaakov-h** [comment]
You could always define `DEBUG` in your production builds 😈

**Comment by orthoxerox** [comment]
@HaloFour 

> Personally I'm on the fence about that as it can result in the application behaving differently depending on whether `DEBUG` is defined.

That's what already happens today when you use `Debug.Assert`.

**Comment by HaloFour** [comment]
@orthoxerox 

> That's what already happens today when you use `Debug.Assert`.

I'm aware.  I've seen this bite some people when they try to assert on something like the return value of a method call which has side-effects and they didn't realize that their method call would also be eliminated.

@alrz 

> It's not behavioural difference, it's just an elided check.

Which becomes a behavioral difference when the method now allows a `null` through in production and that method does some percentage of business logic before it fails, assuming it fails at all.

> we already use Debug.Assert in Roslyn extensively, and it hasn't been a source of confusion?

It's not the people who develop on Roslyn that I would be worried about.  :)

**Comment by YairHalberstadt** [comment]
> Which becomes a behavioral difference when the method now allows a null through in production and that method does some percentage of business logic before it fails, assuming it fails at all.

Presumably this never would have occurred in debug, or it would have hit the assert. And if it did hit the assert and they ignored it, there's little more the language can be expected to do to help.

So the issue might occur if once the production issue occurred they debug it and hit the assert. Well then great! They've found the issue!

**Comment by mikernet** [comment]
@HaloFour The situation you're describing biting people isn't really relevant here as this assertion doesn't have side effects.

Regardless, if someone is failing assertions while debugging and ignoring them, well...what do they think is going to happen in production? I don't see how this is an issue.

**Comment by HaloFour** [comment]
@mikernet 

> Regardless, if someone is failing assertions while debugging and ignoring them, well...what do they think is going to happen in production? I don't see how this is an issue.

Usually the assertion isn't happening during debugging, and it's missed by a unit test due some some bad assumptions.  The code in question could be multiple layers away from some POCO deserialized from JSON where a field described as required suddenly isn't.  These situations very easily make it into production, unfortunately.

**Comment by mikernet** [comment]
@HaloFour Are you talking about an assertion with side effects or this null assertion? 

In the null assertion case it can only help catch the bug you are describing. If it's caught in debugging well then great, you caught the bug. If you didn't and it went to release then you missed the bug and it will be easier to catch when it hits your assertion as you deserialize the faulty data set in debug mode.

**Comment by alrz** [comment]
>The code in question could be multiple layers away from some POCO deserialized from JSON where a field described as required suddenly isn't

That's actually a good example where such assertion could be greatly helpful.

**Comment by mikernet** [comment]
As I mentioned in another thread somewhere, it would be awesome if nullable debug assertions in debug builds could be triggered by a compiler flag. Pretty sure if this was available, best practices would dictate that it be used everywhere possible and everyone would use it. It could either be on/off or configurable to be added for non-null parameter checks and/or when `!` is used in a method body to "de-null" a nullable value.

**Comment by HaloFour** [comment]
@mikernet 

> As I mentioned in another thread somewhere, it would be awesome if nullable debug assertions in debug builds could be triggered by a compiler flag.

I'd be happy with a second preprocessor directive, `#define ENFORCE_NOT_NULL`

**Comment by alrz** [comment]
Note: one could easily redefine the helper with desired ConditionalAttribute (or none at all) - the default impl could use something commonly preferred.

**Comment by HaloFour** [comment]
@alrz 

That might depend on where they emit the helper method and how they call it.  I would imagine that other than flipping the `ConditionalAttribute`s applied to the method that there'd be little reason to define your own.

**Comment by szalapski** [comment]
@mikernet I agree and commented such [here](https://github.com/dotnet/csharplang/issues/2145#issuecomment-575280778).  Perhaps we wouldn't need to mark anything with "!" to enable this.

**Comment by jaroslavurban** [comment]
Not sure if I am late, but why adding new operator '!', instead of using existing '?'? My suggestion would be to use '?' that would define if the parameter shall be checked for ArgumentNullException. The check will be done at IL level and can be explicitly enabled/disabled within some compile setting.

**Comment by theunrepentantgeek** [comment]
> ... can be explicitly enabled/disabled within some compile setting.

￼Computer flags like this introduce different dialects of the language - something the C# team is extremely reluctant to do. 

Keep in mind that each distinct compiler flag doubles the number of C# dialects - a dozen simple flags would mean 4096 subtly different dialects to document and test. Very much not fun. 

Null reference types reached the bar because of the enormous value of detection and elimination of null errors, but it's unlikely that anything else will.

**Comment by MichaelPeter** [comment]
Could this also be extended to additional checks which are very frequent? 

I mean especally string empty checks, my code contains lots of:

```
Guard.CheckNotNullOrEmpty(nameof(myStringParam)), myStringParam); // first argument name, then value to check
or Guard.CheckNotNullOrEmpty(nameof(myStringParam)));
```

Also for things like `Guid.Empty `it could be helpfull but a exclusive priority on string checks woulld be enough.

This is now a bad example but maybe somebody has a better idea:
`void MyMethod([NotStringEmpty] string myStringParam!))`
`void MyMethod([NotStringEmptyOrWhitespace] string myStringParam!))`
`void MyMethod([NotGuidEmptyOrWhitespace] string myStringParam!))`

Or is this more a topic for `ISourceGenerator` ? And standard classes for it?

**Pull request merged**
