### PR TITLE
Fix changes from #537

### PR DESCRIPTION
**Pull request by jamesqo**
See https://github.com/dotnet/csharplang/commit/7d6fe57574f8dce80b62c82d0f75acb3e98f4556#commitcomment-22897524. @jnm2 unintentionally corrected an intentional typo.

/cc @jnm2, @gafter

### CODE REVIEW

**Comment by jnm2** [comment]
@jamesqo Embarrassing that I misunderstood it. Now that I do, the sentence would read more clearly if you say <code>In the **event that</code>.

**Comment by jnm2** [comment]
The proposed wording is not confusing at all now. So sorry about that!

**Comment by ElizaKons** [comment]
test

**Comment by gafter** [comment]
The bullet that is being corrected is being corrected as intended. However, that behavior is one of the kinds of breaking changes we avoid. Specifically, a C# 6 compiler will allow you to write the erroneous code, which would then be an error in C# N. I'd prefer the behavior is to just yield an empty string.

**Comment by jamesqo** [comment]
@gafter 

> I'd prefer the behavior is to just yield an empty string.

Fixed the spec! Thanks for your feedback.

**Comment by jcouv** [comment]
@gafter Ok to merge?

**Comment by jcouv** [comment]
@gafter Ok to merge?

**Pull request merged**
