### PR TITLE
Add a communities document

### PR DESCRIPTION
**Pull request by eyalsk**
Includes links to major C# communities.

### CODE REVIEW

**Comment by tannergooding** [comment]
It may be worth adding some note to the top indicating that the list is non-exhaustive and is not "endorsed". It may also be worth mentioning that they may not be moderated by or even looked at by members of the C# Language Team.

**Comment by tannergooding** [comment]
CC. @jaredpar, @MadsTorgersen

**Comment by eyalsk** [comment]
@tannergooding Sure, I can add that.

**Comment by eyalsk** [comment]
@jaredpar Done.

**Comment by tannergooding** [comment]
Thanks @eyalsk

**Comment by sylveon** [comment]
The Discord invitation link sometimes changes, please use aka.ms/csharp-discord, which is a redirect to the latest valid invite. @tannergooding

**Comment by eyalsk** [comment]
@sylveon I've sent a new [PR](https://github.com/dotnet/csharplang/pull/1783) that fixes that.

**Pull request merged**
