### PR TITLE
Use string interpolation and small fixes

### PR DESCRIPTION
**Pull request by Youssef1313**
- Leave blank lines around snippets.
- Follow code style guidelines.
- Used string interpolation ( Fixes dotnet/docs#14455 )

I noticed that there are no metadata for this `.md` file. Is it missing or there is a reason for that ?

### CODE REVIEW

**Comment by gafter** [comment]
We are not likely to accept stylistic changes until after we have integrated with the ECMA specification and are working on the next version of the specification.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2). Tagging @MadsTorgersen for approval since affects the `specs` folder.

**Review by 333fred — CHANGES_REQUESTED** [review]
We should not be changing the specs folder. Spec changes should happen in dotnet/csharpstandard.

**Comment by Youssef1313** [comment]
Going to close for now. Will possibly do a pass over csharpstandard to be consistent everywhere.

**Pull request closed without merging**
