### PR TITLE
Update conversions.md

### LINKED ISSUE #199: Impossible boxing/unboxing conversions
In the chapters about boxing and unboxing conversions, it is told the following:

> A value type has a boxing conversion to an interface type  I  if it has a boxing conversion to an interface or delegate type  I0  and  I0  is variance-convertible (Variance conversion) to  I .

and

> A value type  S  has an unboxing conversion from an interface type  I  if it has an unboxing conversion from an interface or delegate type  I0  and either  I0  is variance-convertible to  I  or  I  is variance-convertible to  I0  (Variance conversion).

While those sentences are logically true, they seem to tell there are such things as boxing to a delegate or variance-convertion from delegate to interface.

This was mentioned by Eric Lippert in details on his blog two years ago : https://ericlippert.com/2015/05/26/a-different-copy-paste-error/

### PR DESCRIPTION
**Pull request by LouisFr81**
A value-type never has a boxing conversion to a delegate type.
Fixes #199

### CODE REVIEW

**Comment by gafter** [comment]
Please file an issue for the spec bug this is intended to correct. We need the issue to track the change once we pull in the ECMA version of the spec.

**Comment by LouisFr81** [comment]
Is there a reason this hasn't been merged?

**Comment by jcouv** [comment]
Tagging @MadsTorgersen for approval since change affects the `specs` folder (not sure what process we follow there).

**Review by 333fred — COMMENTED** [review]
Changes to the spec happen in the dotnet/csharpstandard repository now.

**Pull request closed without merging**
