### PR TITLE
Repository sync

### PR DESCRIPTION
**Pull request by scottdorman**

### CODE REVIEW

**Comment by alrz** [comment]
What

**Comment by scottdorman** [comment]
@alrz Sorry about that. This was accidentally created trying to get my repo in sync.

**Comment by alrz** [comment]
no need.. just curious what happened! :)

**Comment by orthoxerox** [comment]
I've never been able to do the sync automatically without editing the URL of the comparison page.

**Comment by scottdorman** [comment]
This is the first time I've had issues trying to get a fork to sync up correctly. I'm still not entirely sure what went wrong. I ended up deleting my fork and then creating a new one.

**Comment by alrz** [comment]
`git pull`? you should probably create a new branch from master every time you want to open a PR.

**Pull request closed without merging**
