### PR TITLE
Change heading to H1

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Comment by mairaw** [comment]
@Jcouv can you please review? This is to fix how it's rendering on docs as Bill is working to publish the proposals: https://review.docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/throw-expression?branch=pr-en-us-11026

**Comment by mairaw** [comment]
Well I can't merge, that's why 😄

**Comment by mairaw** [comment]
@BillWagner do you have permissions to merge this?

**Comment by BillWagner** [comment]
@mairaw I do not.

ping @jcouv or @jaredpar to merge.

**Comment by jcouv** [comment]
Oh, my bad. I didn't realize this was a csharplang PR.
Merging!

**Pull request merged**
