### PR TITLE
Added 2013 and 2014 LDM meeting notes. 

### LINKED ISSUE #8: Add pre-2015 meeting notes
LDM meeting notes from 2015 onward are being added to this repository in #7. However, meeting notes from October 2013 through the end of 2014 are (linked) in 

- http://roslyn.codeplex.com/wikipage?title=CSharp%20Language%20Design%20Notes&referringTitle=Documentation

and

- http://roslyn.codeplex.com/wikipage?title=Visual%20Basic%20Language%20Design%20Notes&referringTitle=Documentation

Although their source is in markdown form, only the author can easily see the markdown source. So can I please have some help, either from an administrator, or from @MadsTorgersen and Lucian, on getting the markdown source for those?

### PR DESCRIPTION
**Pull request by scottdorman**
Fixes #8.

### CODE REVIEW

**Comment by gafter** [comment]
This is awesome! How did you get the raw markdown?

**Comment by scottdorman** [comment]
After poking around in the rendered HTML on CodePlex, it turned out that the original markdown for each post was stored in a `data-markdown` attribute on the `td` element. Once I saw that, I wrote a quick and dirty screen scraper using the HtmlAgilityPack and had it pull out the markdown and piece it all together in together into a file. The result wasn't 100% clean (since some of the original posts had the actual LDM notes spread out over multiple table rows) so there was a little bit of manual cleanup needed but not much. The README files were done completely by hand though.

**Comment by gafter** [comment]
This appears to have imported the discussion along with the LDM notes. Can you please remove the discussion?

**Comment by scottdorman** [comment]
Yes, I can do that. I wasn't sure if we wanted to include the discussions or not, so I opted to include them initially. Since I'm removing them, should I merge the multi-part meeting notes in to a single file as well?

**Comment by gafter** [comment]
No, please keep the multi-part meeting notes in their original form.

**Comment by gafter** [comment]
@scottdorman Thank you so much for doing this!

**Comment by scottdorman** [comment]
@gafter You're welcome!

**Pull request merged**
