### PR TITLE
Add support for common type of `int` and `double?`.

### PR DESCRIPTION
**Pull request by gafter**
See https://github.com/dotnet/csharplang/issues/881

As requested by LDM about a year ago

### CODE REVIEW

**Comment by gafter** [comment]
@MadsTorgersen @dotnet/ldm Could someone please look at this and verify that it is as expected?

**Comment by alrz** [comment]
There's a prototype over at https://github.com/alrz/roslyn/commit/67f9a3a119254d4aa965b71ed17cc6902e40ef50.

**Comment by alrz** [comment]
@gafter Can you please take a look at the above commit to see if it's using the right approach. Thanks.

**Comment by gafter** [comment]
I will look at it when back from vacation on Monday.

**Comment by alrz** [comment]
HashSet can handle a `null` value, in the next iteration I'm going to use `null` to signify a null literal in the BestType algorithm. btw should this change include target-typing for `:?` and `??` expressions? If so I'd be happy to take a stab at it.

**Comment by gafter** [comment]
@alrz I don't think the approach you are taking addresses the problem described in the title of this issue.  See also https://github.com/dotnet/csharplang/issues/881

If we target-type `??` and `?:` as we plan to, there will be less motivation for making this change.

**Comment by alrz** [comment]
It's buried in the diff https://github.com/alrz/roslyn/blob/645c343114b9eec2c069242d231cfce95af1e40c/src/Compilers/CSharp/Test/Semantic/Semantics/NullableEnhancedCommonTypeTests.cs

 I think the compiler yields the correct result for both `int?/double => double?` and `double/null => double?` however, as I saw in that prototype (at least the way I wrote it), doing either of cases just does not fit into the current way of how things are done, we need to make a lot of exceptions and whatnot. 

>If we target-type ?? and ?: as we plan to, there will be less motivation for making this change.

makes sense. target-typing of those would have the same effect. 👍

**Pull request merged**
