### PR TITLE
Fix invalid character in unsafe-code.md

### PR DESCRIPTION
**Pull request by niklaskarl**
A invisible control character prevented the title from being displayed correctly.

### CODE REVIEW

**Comment by svick** [comment]
It's not just unsafe-code, it seems all the other documents contain the invisible BOM character too.

**Comment by gafter** [comment]
The title looks OK to me: https://github.com/dotnet/csharplang/blob/master/spec/unsafe-code.md

**Comment by svick** [comment]
@gafter This PR was made shortly after [GitHub switched to new markdown parser](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown), so maybe it was a bug in it that was since fixed?

**Comment by gafter** [comment]
Since there no longer appears to be a problem here, closing.

**Pull request closed without merging**
