### PR TITLE
Add docs task to the feature template

### PR DESCRIPTION
**Pull request by BillWagner**
@jcouv @jaredpar @MadsTorgersen @KathleenDollard

### CODE REVIEW

**Comment by 333fred** [comment]
To be entirely honest, we don't use the existing checklist items basically ever. I've been meaning to propose we find a different way to track progress.

**Comment by 333fred** [comment]
Well, this is part of docs item to better surface C# proposals. If we want to do that, I think we should do a bigger revamp of that progress section.

**Review by jcouv — APPROVED** [review]

**Comment by jcouv** [comment]
Sure. We can make further changes. Would be happy to remove the Prototype and Implementation status which we didn't use much (just keep the Spec and Docs link).

**Comment by BillWagner** [comment]
> Well, this is part of docs item to better surface C# proposals. If we want to do that, I think we should do a bigger revamp of that progress section.

The motivation for this was to make it easy for anyone that finds these issues (from SO, or whatever) to have a roadmap to the full story (as completed): the proposal, LDM notes on updates, the PRs for the change, and the docs for the final feature.

**Comment by 333fred** [comment]
> The motivation for this was to make it easy for anyone that finds these issues (from SO, or whatever) to have a roadmap to the full story (as completed): the proposal, LDM notes on updates, the PRs for the change, and the docs for the final feature.

Right. My concern is that these status sections are never updated and are not a good way to communicate info currently.

**Pull request closed without merging**
