### PR TITLE
ModuleInitializerAttribute should not be emitted as a custom attribute

### PR DESCRIPTION
**Pull request by jnm2**
Requested by @RikkiGibson for https://github.com/dotnet/roslyn/pull/46634.

### CODE REVIEW

**Comment by ufcpp** [comment]
How about SkipLocalsInit?

**Comment by jnm2** [comment]
I wholeheartedly agree about that one. @RikkiGibson Can we hit both at once?

**Comment by jnm2** [comment]
@RikkiGibson I have a feeling a conclusion was reached but I can't find it in our last conversation.

Also, SkipLocalsInit ask: https://github.com/dotnet/csharplang/issues/1738#issuecomment-666310953

**Comment by jnm2** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
