### PR TITLE
Rename statics-in-interfaces.md to static-abstracts-in-interfaces.md

### PR DESCRIPTION
**Pull request by RikkiGibson**
When I went looking for the "static abstract members in interfaces" proposal, I was a little confused by the current file name, since static members are allowed in interfaces prior to this proposal. Please consider this alternate file name.

### CODE REVIEW

**Review by jcouv — APPROVED** [review]
LGTM but may need to fix links to this document from roslyn repo (test plan) and csharplang (feature proposal).

**Review by 333fred — APPROVED** [review]
LGTM, please make sure you fix up the roslyn repo before merging.

**Comment by RikkiGibson** [comment]
Please take a look @AlekseyTs

**Comment by AlekseyTs** [comment]
I have no objection to the rename. Just an FYI, the file was created and named by @MadsTorgersen.

**Comment by RikkiGibson** [comment]
Thanks. I didn't find any references to this filename in csharplang, and I submitted a PR to fix up the one reference I saw in the Roslyn feature branch. I will merge this now and we can move to merge the PR on the Roslyn side after that.

**Pull request merged**
