### PR TITLE
Create DeleteThis

### PR DESCRIPTION
**Pull request by alanfelipej**

### CODE REVIEW

**Comment by yaakov-h** [comment]
This looks like a bad-faith attempt at Hacktoberfest. Can I suggest to label this PR as "invalid"?

**Comment by alanfelipej** [comment]
I was just testing how to create PR from github on the browser, sorry!

**Comment by alanfelipej** [comment]
u can close it if u want to

**Comment by yaakov-h** [comment]
You had to test that exactly five times on different repositories, in the last 48 hours of the month?

**Comment by tannergooding** [comment]
> I was just testing how to create PR from github on browser, sorry!

I would suggest trying this on a personal repo, which gives you all the same benefits as doing it to an external repo, but without adding unnecessary notifications, overhead, etc for everyone subscribed to a repo such as this.

**Pull request closed without merging**
